---
title: "Best practices feedback loop"
---

* LLMs amplify best practices, and make them more achievable
* Virtuous cycle: where as you improve tests and docs, it makes it easier for agents to work with your package. 
* Really good news for non-professional developers
* You can do as you go, but also useful to batch up as part of regular upkeep

# Code style

## Just use air

* No longer worth manually enforcing a coding style
* Just use `air`
* Get started with `usethis::use_air()` + `Air: format workspace file`.
* (If you're using the Claude Code extension, it won't know where to find the `air` binary. You can tell that it's bundled in )

## Beware excessive comments

* Agents (esp. Claude) LOVE to write wordy comments
* Sometimes the comments are useful; often they are not
* Code-comment mismatch more dangerous with agents

* Comments should explain the why
* Comments shouldn't need to explain the what
* Comments shouldn't explain how we got here

* I've had relatively little success prompting this behaviour away
* Better luck with prompt to remove

# Unit testing

## Agents love to write tests

* Generally don't need to explicitly ask for them
* (Assuming you have tests already set up e.g. with `use_testthat()`)
* Explicitly request code coverage
* May want to explicitly request TDD (i.e. write the test first)

## Your job is to:

* Keep them well organised
  * "Tests for R/{foo}.R should live in tests/testhat/test-{foo}.R"
* Keep them fast
  * "Parallelise these tests"
  * "Use SlowReporter and speed up the slowest tests"
  * "Compare coverage before and after"
* Keep them minimal
  * "Carefully consider the tests "

* All these tasks are faciliated by relatively fine grained R and test files
* You can ask the agent to refactor

## Test coverage

* Previously 100% test coverage was not worth it.
* Probably worth reconsidering now.

## Test maintenance

* Worth asking to minimise tests, to group related tests together
* Make sure

# Documentation

* Reserve `AGENTS.md` for agents only 
* Use `README.md` for humans + agents
* If you want people to take your package seriously, worth spending human time on your README and vignettes.
* IMO Kimi is a better writer than Claude, but still plenty of LLMism

# Performance

## Overview

* LLMs are very good at improving the performance of code. 
* They are better than me at reading the results of `RProf()`. 
* They are better than me at writing C/C++ code.
* They are not very good at experimental design.
* They are not very good at managing complexity/performance tradeoffs.

## Prompting

* "Make XXX faster"
* Make sure it's well tested first
* Ensure it records its work
* Request both microbenchmarks and meaningful user actions
* Pay attention to what it's doing

## C/C++

* Previously C++ (via Rcpp/cpp11) had good balance of effort vs. results
* Now for small amounts of compiled code, pure C has no dependencies and LLMs are good at writing it.
* You will need to give it hints as to latest C API.

# CI/CD

* Agents know more about writing GitHub actions than I do.
* `use_github_action()` for common stuff
* Use agents for anything custom
* Agents are also great at fixing problems thus revealed

# Contributing upstream

* You can now use these skills to fix problems upstream that might have previously been out of reach.
* The primary drawback of this is maintainer overload
* Your job is to bring your human judgement and expertise into play.
* Be upfront about AI usage. 
* Spend human time on communication.
* Don't be a meat proxy.
